language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

script: "./gradlew clean build"

before_deploy:
  - echo $(li)
  - mkdir -p before-deploy
  #- cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/rest-api.zip

deploy:
    - provider: s3
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key: $AWS_SECRET_KEY

      bucket: jimmyberg-rest-api
      region: ap-northeast-2
      skip_cleanup: true
      acl: private
      local_dir: deploy
      wait_until_deployed: true

    - provider: codedeploy
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key: $AWS_SECRET_KEY

      bucket: jimmyberg-rest-api
      key: rest-api.zip
      bundle_type: zip
      application: rest-api
      deployment_group: rest-api-group
      region: ap-northeast-2
      wait_until_deployed: true

notifications:
  email:
    recipients:
      - jimmyberg.kim@gmail.com
