language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

script: "./gradlew clean build"

before_deploy:
  - zip -r rest-api ./*
  - mkdir -p deploy
  - mv rest-api.zip deploy/rest-api.zip

deploy:
    - provider: codedeploy
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key: $AWS_SECRET_KEY

      bucket: jimmyberg-rest-api
      key: rest-api.zip
      bundle_type: zip
      application: spring-rest-api
      deplyment_group: spring-rest-api-group
      region: ap-northeast-2
      skip_cleanup: true
      acl: private
      local_dir: deploy
      wait_until_deployed: true

notifications:
  email:
    recipients:
      - jimmyberg.kim@gmail.com
