spring:
  profiles: real
  url:
    base: http://13.209.75.145:8080

logging:
  level:
    root: warn
    com.demo.restapi: debug
  file:
    path: /home/ec2-user/logs/rest-api
    max-history: 7

server:
  port: 8081
