spring:
  profiles:
    active: local
    include: db

  messages:
    basename: i18n/exception
    encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate:
      hbm2ddl.auto: none
      format_sql: true
    generate-ddl: true
    open-in-view: false

  social:
    kakao:
      client_id: 88b1334af4bd80a7112a81e94c774817
      redirect: /social/login/kakao
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me

  public-api:
    park-place:
      api-url: http://api.data.go.kr/openapi/tn_pubr_prkplce_info_api
      service-key: LGg12%2B%2BRNPBk4ZoSIVuownxLrJ74ELJDhzOnqYDNuBuxr1I4eQdRcAaAhOk8awaeveye8QG5TTVhIr19psJrQw%3D%3D
    car-wash:
      api-url: http://api.data.go.kr/openapi/tn_pubr_public_carwsh_api
      service-key: LGg12%2B%2BRNPBk4ZoSIVuownxLrJ74ELJDhzOnqYDNuBuxr1I4eQdRcAaAhOk8awaeveye8QG5TTVhIr19psJrQw%3D%3D

  jwt:
    secret: govlepel@$&

  redis:
    host: redis-cache-cluster.bklsy6.ng.0001.apn2.cache.amazonaws.com
    port: 6379

springdoc:
  title: REST API demo
  version: v0.0.1
  # Application 의 API 를 OAS 3 이용하여 json 형식화
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json # request media type
  default-produces-media-type: application/json # response media type
  swagger-ui:
    path: /swagger-ui.html                      # swagger HTML 문서 경로
    operations-sorter: method                   # controller 내에서 정의한 API 정렬 순서 (alpha : 알파벳 오름차순)
    tags-sorter: alpha                          # tag 정렬 순서
    disable-swagger-default-url: true           # swagger default petstore HTML 문서 비활성화 여부
    display-query-params-without-oauth2: true   # json config file 대신 parameter 를 이용한 swagger-ui 접근 (v1.4.1이상 지원)
  # 문서화할 API path 목록
  paths-to-match:
    - /api/**
