spring:
  profiles:
    active: local
    include: db

  messages:
    basename: i18n/exception
    encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate:
      hbm2ddl.auto: none
      format_sql: true
    generate-ddl: true
    open-in-view: false

  social:
    kakao:
      client_id: 88b1334af4bd80a7112a81e94c774817
      redirect: /social/login/kakao
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me

  public-api:
    park-place:
      api-url: http://api.data.go.kr/openapi/tn_pubr_prkplce_info_api
      service-key: LGg12%2B%2BRNPBk4ZoSIVuownxLrJ74ELJDhzOnqYDNuBuxr1I4eQdRcAaAhOk8awaeveye8QG5TTVhIr19psJrQw%3D%3D
    car-wash:
      api-url: http://api.data.go.kr/openapi/tn_pubr_public_carwsh_api
      service-key: LGg12%2B%2BRNPBk4ZoSIVuownxLrJ74ELJDhzOnqYDNuBuxr1I4eQdRcAaAhOk8awaeveye8QG5TTVhIr19psJrQw%3D%3D

  jwt:
    secret: govlepel@$&

  redis:
    host: redis-cache-cluster.bklsy6.ng.0001.apn2.cache.amazonaws.com
    port: 6379

