spring:
  profiles: alpha
  url:
    base: http://13.209.75.145:8080
  datasource:
    url: jdbc:mariadb://spring-rest-api.ct1sm8fccuaj.ap-northeast-2.rds.amazonaws.com/spring_rest_api
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: dustp909$
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate:
      hbm2ddl.auto: none
      format_sql: true
    show-sql: true
    generate-ddl: false

logging:
  level:
    root: warn
    com.demo.restapi: info
    path: /home/ec2-user/demo/restapi/log
  file:
    max-history: 7
