spring:
  profiles: local
  url:
    base: http://localhost:8080
  datasource:
    url: jdbc:mariadb://spring-rest-api.ct1sm8fccuaj.ap-northeast-2.rds.amazonaws.com/spring_rest_api
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: dustp909$
  h2:
    console:
      enabled: true
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    properties.hibernate:
#      hbm2ddl.auto: update
#      format_sql: true
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update

logging:
  level:
    root: warn
    com.demo.restapi: debug
