spring:
  profiles: alpha
  url:
    base: http://13.209.75.145:8080
  datasource:
    url: jdbc:mariadb://spring-rest-api.ct1sm8fccuaj.ap-northeast-2.rds.amazonaws.com/spring_rest_api
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: dustp909$

logging:
  level:
    root: warn
    com.demo.restapi: info
  file:
    path: /home/ec2-user/logs
    max-history: 7
